spring:
  application:
    name: userService
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_user_db
    username: root
    password: Deepak@3703

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

